services:
  jmcomic-api:
    image: orwellz/jmcomic-api:latest
    container_name: jmcomic-api
    ports:
      - "8699:8699"
    volumes:
      - ./pdf:/app/pdf
      - ./webp:/app/webp
    restart: unless-stopped